### ISSUE TITLE
Book edits not being saved upon exiting GUI

### ISSUE THREAD

**Issue by BLOKBUSTR** [KosmoMoustache/FixBookGUI#10]
I am using the latest version 1.4 for Minecraft 1.20.1.

Reproduction steps:
1. Install mod for 1.20.1
2. Open a world and obtain a Book & Quill
3. Write anything in the book and click "Done" (do not use escape key)
4. Reopen the book to examine its contents

I am aware that pressing the escape key does not save edited contents by default, but clicking the "Done" button should. In my case however, even clicking "Done" apparently does not save any edits I have made in the book. I have temporarily removed this mod and found that it is indeed causing this issue.

I have also noticed that mouse click events are still not translated to the correct position as mentioned in #4, such as whenever I'm clicking to a previous line to edit it.

**Comment by BLOKBUSTR** [comment]
I have just tested with a tooltip event and found that the hover area is placed several lines lower than the actual text. Clicking to different lines is still offset to the top of the screen (as in Vanilla).

**Comment by KosmoMoustache** [comment]
Hey, sorry for the late response, i didn't have access to a proper computer.
I've fixed the bugs

Again sorry the the late response

**Comment by BLOKBUSTR** [comment]
No worries for the timing at all. Everything works flawlessly now, thank you!
