### ISSUE TITLE
Curseforge file 1.20.2-1.5 is labeled for 1.20.1

### ISSUE THREAD

**Issue by Artwind2** [KosmoMoustache/FixBookGUI#18]
Despite the version labeled as 1.20.2 in the file name, on curseforge it is also enabled for 1.20.1 in the game versions tab.
It results in some troubles when using the button "update all mods", and having to revert the 1.4.1 file manually.
![2023-12-17 23_42_07-CurseForge](https://github.com/KosmoMoustache/FixBookGUI/assets/38019992/3825b9d3-b1a0-4e36-9a4f-44aa58b13279)

**Comment by KosmoMoustache** [comment]
I don't understand, none of the version is registered for multiple Minecraft version. And it don't appear on the website, only in the CurseForge app.
I'm sorry but I think the problem comes from CurseForge

**Comment by Artwind2** [comment]
The mod is now up to date. You must have change something that fixed the issue while looking at the problem :)
