### ISSUE TITLE
Text Cursor Wrong Position

### ISSUE THREAD

**Issue by J4PC** [KosmoMoustache/FixBookGUI#23]
![Unbenannt](https://github.com/KosmoMoustache/FixBookGUI/assets/97805057/7a66516c-4d99-4329-b1ae-434ff18deff4)

If you want to select, for example, a word with your mouse, it doesn't work. 
**The old, not-fixed position of the book needs to be clicked.**

**Comment by KosmoMoustache** [comment]
Which version?

**Comment by J4PC** [comment]
fixbookgui-1.6.0+1.20.4

**Comment by KosmoMoustache** [comment]
Fixed in 1.6.1 thanks you for reporting this issue
