### ISSUE TITLE
Unable to load into a world in 1.20.5

### ISSUE THREAD

**Issue by J4PC** [KosmoMoustache/FixBookGUI#25]
![image](https://github.com/KosmoMoustache/FixBookGUI/assets/97805057/ba596f4f-419b-4d03-a990-77ee627f7aa0)
Even when you want to join a singleplayer world, there is a network protocol error which leads you into the multiplayer menu.

farbic-loader-0.15.10-1.20.5 **using the mods:**
- fixbookgui-1.6.1+1.20.4
- fabric-api-0.97.6+1.20.5

**Comment by KosmoMoustache** [comment]
You can get the version for 1.20.5 on [modrinth ](https://modrinth.com/mod/fixbookgui/version/1.6.1+1.20.5) or [github ](https://github.com/KosmoMoustache/FixBookGUI/releases/tag/v1.20.5-1.6.1)now
