### ISSUE TITLE
Incompatible with 1.21

### ISSUE THREAD

**Issue by J4PC** [KosmoMoustache/FixBookGUI#26]
If you start your game, you get incompatible mods found, fabric pop up.

**Comment by KosmoMoustache** [comment]
Works fine on my computer. Are you sure you have installed the latest cloth-config, mod menu and fabric api version?

**Comment by KosmoMoustache** [comment]
My bad, it taught is was my other project, i'm looking into it

**Comment by KosmoMoustache** [comment]
New version should be available in couples of minutes, thanks you for your report
