### ISSUE TITLE
Is this mod dead or still alive? there is no discord to ask about

### ISSUE THREAD

**Issue by Nukecraft5419** [KosmoMoustache/FixBookGUI#6]

**Comment by KosmoMoustache** [comment]
Still alive but i don't have access to a pc right now, it will be update in a week or two

**Comment by Nukecraft5419** [comment]
Perfect thank you very much from the LifeMC Studios team we await

**Comment by KosmoMoustache** [comment]
And there you go:
[https://modrinth.com/mod/fixbookgui/version/RzNm4GZF](https://modrinth.com/mod/fixbookgui/version/RzNm4GZF)

**Comment by Nukecraft5419** [comment]
Yes indeed the first download and my team put it in 1.18.2, 1.19.4, 1.20.1
